name:                lethe
version:             0.1.0.0
github:              "ngyj/lethe"
license:             BSD3
author:              "ngyj"
maintainer:          "ngyj@cinnabar.fr"
copyright:           "2019 ngyj"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ngyj/lethe#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- microlens
- microlens-th
- cmdargs
- hashable
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  lethe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lethe

tests:
  lethe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lethe
